eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/
server:
  port: 8084
spring:
  application:
    name: gateway
zuul:
  routes:
    api:
      path: /api/**
      serviceId: eurekaprovider

